---
date: 2023-04-20
type: note
tags: ankify
---

You can raise your own exceptions using the `raise Exception("This is an error")`.

You can use assertions to catch errors early using the `assert *condition*, "This is an error"`. If the condition is not true, then the program will terminate and throw the error.
